limit_req_zone $binary_remote_addr zone=mylimit:10m rate=15r/m;
limit_req_status 429;
server {
    listen 80;

    location ~ /metrics$ {
        return 404;
    }

    location /auth/ {
        limit_req zone=mylimit burst=5 nodelay;
        proxy_pass http://accounts_service:8081/; 
        proxy_set_header Host $host;
    }

    location /resource/ {
        limit_req zone=mylimit burst=5 nodelay;
        proxy_pass http://resource_service:8082/;
        proxy_set_header Host $host;
    }
}
